import type { Challenge } from "./types";

// Curated catalog. Queries are portable ANSI SQL where possible.
// Challenges use the built-in E-Commerce sample (users, inventory, shipments).
// Tables assumed: users(user_id, name, email, country, signup_date, is_active),
// inventory(item_id, name, category, price, stock, rating),
// shipments(shipment_id, user_id, item_id, status, shipped_at, delivered_at).

let n = 0;
const nx = () => ++n;

export const CHALLENGES: Challenge[] = [
  // --- SELECT Basics ---
  {
    id: "sel-01",
    number: nx(),
    title: "Retrieve all users",
    topic: "select-basics",
    difficulty: "Beginner",
    estMinutes: 3,
    xp: 10,
    concepts: ["SELECT", "FROM"],
    tags: ["basics", "select"],
    domain: "E-Commerce",
    problem: "Return every column and every row from the users table.",
    dbDescription: "users(user_id, name, email, country, signup_date, is_active)",
    sampleInput: "SELECT * FROM users LIMIT 3;",
    expectedOutput: "All rows and columns from users.",
    starterSql: "-- Select every row and column from users\n",
    hints: ["Use SELECT * to grab every column.", "FROM tells SQL which table to read."],
    solution: "SELECT * FROM users;",
    explanation: "SELECT * projects every column of the source table.",
    complexity: "O(n)",
    conceptsLearned: ["SELECT", "FROM", "Projection"],
  },
  {
    id: "sel-02",
    number: nx(),
    title: "Names and emails only",
    topic: "select-basics",
    difficulty: "Beginner",
    estMinutes: 3,
    xp: 10,
    concepts: ["SELECT", "column list"],
    tags: ["basics"],
    domain: "E-Commerce",
    problem: "Return only the name and email columns from users.",
    dbDescription: "users table",
    sampleInput: "SELECT name, email FROM users LIMIT 3;",
    expectedOutput: "Two columns: name, email.",
    starterSql: "-- Project just name and email\n",
    hints: ["List columns after SELECT.", "Separate them with commas."],
    solution: "SELECT name, email FROM users;",
    explanation: "Explicit column lists reduce data transfer and clarify intent.",
    complexity: "O(n)",
    conceptsLearned: ["Column projection"],
  },
  {
    id: "sel-03",
    number: nx(),
    title: "Alias a column",
    topic: "select-basics",
    difficulty: "Beginner",
    estMinutes: 3,
    xp: 10,
    concepts: ["SELECT", "AS"],
    tags: ["alias"],
    domain: "E-Commerce",
    problem: "Return the name column aliased as customer_name.",
    dbDescription: "users table",
    sampleInput: "",
    expectedOutput: "One column named customer_name.",
    starterSql: "",
    hints: ["Use the AS keyword.", "Aliases can be quoted if they contain spaces."],
    solution: "SELECT name AS customer_name FROM users;",
    explanation: "Aliases rename output columns without changing the underlying schema.",
    complexity: "O(n)",
    conceptsLearned: ["Aliases"],
  },

  // --- WHERE & Filtering ---
  {
    id: "whr-01",
    number: nx(),
    title: "Only active users",
    topic: "where-filtering",
    difficulty: "Beginner",
    estMinutes: 4,
    xp: 15,
    concepts: ["WHERE", "boolean"],
    tags: ["filter"],
    domain: "E-Commerce",
    problem: "Return all users where is_active = 1.",
    dbDescription: "users table",
    sampleInput: "",
    expectedOutput: "Only active users.",
    starterSql: "",
    hints: ["Use WHERE.", "Compare with = 1."],
    solution: "SELECT * FROM users WHERE is_active = 1;",
    explanation: "WHERE filters rows based on a boolean predicate.",
    complexity: "O(n)",
    conceptsLearned: ["WHERE", "Predicates"],
  },
  {
    id: "whr-02",
    number: nx(),
    title: "Items priced above 50",
    topic: "where-filtering",
    difficulty: "Beginner",
    estMinutes: 4,
    xp: 15,
    concepts: ["WHERE", ">"],
    tags: ["filter"],
    domain: "E-Commerce",
    problem: "Return inventory items whose price is greater than 50.",
    dbDescription: "inventory table",
    sampleInput: "",
    expectedOutput: "Items with price > 50.",
    starterSql: "",
    hints: ["Compare price to 50.", "Use the > operator."],
    solution: "SELECT * FROM inventory WHERE price > 50;",
    explanation: "Numeric comparisons work with =, <>, <, >, <=, >=.",
    complexity: "O(n)",
    conceptsLearned: ["Comparison operators"],
  },
  {
    id: "whr-03",
    number: nx(),
    title: "Users from two countries",
    topic: "where-filtering",
    difficulty: "Intermediate",
    estMinutes: 5,
    xp: 20,
    concepts: ["IN"],
    tags: ["filter", "IN"],
    domain: "E-Commerce",
    problem: "Return users whose country is either 'US' or 'UK'.",
    dbDescription: "users table",
    sampleInput: "",
    expectedOutput: "US or UK users.",
    starterSql: "",
    hints: ["Use IN (…).", "Equivalent: OR chain."],
    solution: "SELECT * FROM users WHERE country IN ('US','UK');",
    altSolution: "SELECT * FROM users WHERE country = 'US' OR country = 'UK';",
    explanation: "IN is a compact way to express membership.",
    complexity: "O(n)",
    conceptsLearned: ["IN operator"],
  },

  // --- ORDER BY ---
  {
    id: "ord-01",
    number: nx(),
    title: "Sort users by signup date",
    topic: "order-by",
    difficulty: "Beginner",
    estMinutes: 3,
    xp: 10,
    concepts: ["ORDER BY"],
    tags: ["sort"],
    domain: "E-Commerce",
    problem: "Return users sorted by signup_date ascending.",
    dbDescription: "users table",
    sampleInput: "",
    expectedOutput: "Users sorted oldest first.",
    starterSql: "",
    hints: ["Use ORDER BY.", "ASC is the default."],
    solution: "SELECT * FROM users ORDER BY signup_date ASC;",
    explanation: "ORDER BY sorts the result set on one or more expressions.",
    complexity: "O(n log n)",
    conceptsLearned: ["ORDER BY"],
  },
  {
    id: "ord-02",
    number: nx(),
    title: "Top priced items first",
    topic: "order-by",
    difficulty: "Beginner",
    estMinutes: 3,
    xp: 10,
    concepts: ["ORDER BY DESC"],
    tags: ["sort"],
    domain: "E-Commerce",
    problem: "Return inventory sorted by price descending.",
    dbDescription: "inventory",
    sampleInput: "",
    expectedOutput: "Highest priced first.",
    starterSql: "",
    hints: ["DESC reverses order.", "Ties handled by original position."],
    solution: "SELECT * FROM inventory ORDER BY price DESC;",
    explanation: "DESC yields descending order.",
    complexity: "O(n log n)",
    conceptsLearned: ["DESC"],
  },

  // --- LIMIT & OFFSET ---
  {
    id: "lim-01",
    number: nx(),
    title: "First 5 users",
    topic: "limit-offset",
    difficulty: "Beginner",
    estMinutes: 3,
    xp: 10,
    concepts: ["LIMIT"],
    tags: ["pagination"],
    domain: "E-Commerce",
    problem: "Return the first 5 users by user_id.",
    dbDescription: "users",
    sampleInput: "",
    expectedOutput: "Five rows.",
    starterSql: "",
    hints: ["ORDER first.", "Then LIMIT 5."],
    solution: "SELECT * FROM users ORDER BY user_id LIMIT 5;",
    explanation: "LIMIT caps how many rows the engine returns.",
    complexity: "O(n log n)",
    conceptsLearned: ["LIMIT"],
  },
  {
    id: "lim-02",
    number: nx(),
    title: "Second page of items",
    topic: "limit-offset",
    difficulty: "Intermediate",
    estMinutes: 5,
    xp: 20,
    concepts: ["LIMIT", "OFFSET"],
    tags: ["pagination"],
    domain: "E-Commerce",
    problem: "Skip the first 5 inventory rows and return the next 5.",
    dbDescription: "inventory",
    sampleInput: "",
    expectedOutput: "Rows 6-10.",
    starterSql: "",
    hints: ["OFFSET skips rows.", "Combine LIMIT and OFFSET."],
    solution: "SELECT * FROM inventory ORDER BY item_id LIMIT 5 OFFSET 5;",
    explanation: "Pagination = (page-1) * page_size as OFFSET.",
    complexity: "O(n log n)",
    conceptsLearned: ["OFFSET"],
  },

  // --- DISTINCT ---
  {
    id: "dst-01",
    number: nx(),
    title: "Unique countries",
    topic: "distinct",
    difficulty: "Beginner",
    estMinutes: 3,
    xp: 10,
    concepts: ["DISTINCT"],
    tags: ["dedupe"],
    domain: "E-Commerce",
    problem: "List each country only once from users.",
    dbDescription: "users",
    sampleInput: "",
    expectedOutput: "Distinct countries.",
    starterSql: "",
    hints: ["SELECT DISTINCT.", "Order by the same column for readability."],
    solution: "SELECT DISTINCT country FROM users ORDER BY country;",
    explanation: "DISTINCT removes duplicates from the projected columns.",
    complexity: "O(n)",
    conceptsLearned: ["DISTINCT"],
  },

  // --- Aggregate Functions ---
  {
    id: "agg-01",
    number: nx(),
    title: "Count all users",
    topic: "aggregate-functions",
    difficulty: "Beginner",
    estMinutes: 3,
    xp: 10,
    concepts: ["COUNT"],
    tags: ["aggregate"],
    domain: "E-Commerce",
    problem: "Return the total number of users.",
    dbDescription: "users",
    sampleInput: "",
    expectedOutput: "One row, one column with the count.",
    starterSql: "",
    hints: ["COUNT(*).", "No GROUP BY needed."],
    solution: "SELECT COUNT(*) AS total FROM users;",
    explanation: "COUNT(*) returns the row count of the input.",
    complexity: "O(n)",
    conceptsLearned: ["COUNT"],
  },
  {
    id: "agg-02",
    number: nx(),
    title: "Average item price",
    topic: "aggregate-functions",
    difficulty: "Beginner",
    estMinutes: 3,
    xp: 15,
    concepts: ["AVG"],
    tags: ["aggregate"],
    domain: "E-Commerce",
    problem: "Return the average price of inventory items.",
    dbDescription: "inventory",
    sampleInput: "",
    expectedOutput: "One row with avg_price.",
    starterSql: "",
    hints: ["AVG().", "Alias the result."],
    solution: "SELECT AVG(price) AS avg_price FROM inventory;",
    explanation: "AVG ignores NULLs and returns the arithmetic mean.",
    complexity: "O(n)",
    conceptsLearned: ["AVG"],
  },
  {
    id: "agg-03",
    number: nx(),
    title: "Min, max, and total stock",
    topic: "aggregate-functions",
    difficulty: "Intermediate",
    estMinutes: 5,
    xp: 20,
    concepts: ["MIN", "MAX", "SUM"],
    tags: ["aggregate"],
    domain: "E-Commerce",
    problem: "Return the min, max, and sum of stock across inventory as min_s, max_s, total_s.",
    dbDescription: "inventory",
    sampleInput: "",
    expectedOutput: "One row, three columns.",
    starterSql: "",
    hints: ["Combine aggregates in one SELECT.", "Alias each output."],
    solution: "SELECT MIN(stock) AS min_s, MAX(stock) AS max_s, SUM(stock) AS total_s FROM inventory;",
    explanation: "Multiple aggregates can be selected together over the same input.",
    complexity: "O(n)",
    conceptsLearned: ["MIN", "MAX", "SUM"],
  },

  // --- GROUP BY ---
  {
    id: "grp-01",
    number: nx(),
    title: "Users per country",
    topic: "group-by",
    difficulty: "Intermediate",
    estMinutes: 5,
    xp: 20,
    concepts: ["GROUP BY", "COUNT"],
    tags: ["group"],
    domain: "E-Commerce",
    problem: "Return each country and the number of users in it.",
    dbDescription: "users",
    sampleInput: "",
    expectedOutput: "country, user_count.",
    starterSql: "",
    hints: ["GROUP BY country.", "COUNT(*) per group."],
    solution: "SELECT country, COUNT(*) AS user_count FROM users GROUP BY country;",
    explanation: "GROUP BY partitions rows; aggregates apply per partition.",
    complexity: "O(n)",
    conceptsLearned: ["GROUP BY"],
  },
  {
    id: "grp-02",
    number: nx(),
    title: "Average price per category",
    topic: "group-by",
    difficulty: "Intermediate",
    estMinutes: 5,
    xp: 20,
    concepts: ["GROUP BY", "AVG"],
    tags: ["group"],
    domain: "E-Commerce",
    problem: "Return each category and its average price ordered by average descending.",
    dbDescription: "inventory",
    sampleInput: "",
    expectedOutput: "category, avg_price.",
    starterSql: "",
    hints: ["GROUP BY category.", "ORDER BY the aggregate."],
    solution: "SELECT category, AVG(price) AS avg_price FROM inventory GROUP BY category ORDER BY avg_price DESC;",
    explanation: "You may sort by aliased aggregate columns.",
    complexity: "O(n)",
    conceptsLearned: ["GROUP BY", "AVG"],
  },

  // --- HAVING ---
  {
    id: "hav-01",
    number: nx(),
    title: "Popular countries",
    topic: "having",
    difficulty: "Intermediate",
    estMinutes: 6,
    xp: 25,
    concepts: ["HAVING"],
    tags: ["group", "filter"],
    domain: "E-Commerce",
    problem: "Return countries that have more than 1 user.",
    dbDescription: "users",
    sampleInput: "",
    expectedOutput: "country, user_count where user_count > 1.",
    starterSql: "",
    hints: ["HAVING filters groups.", "It applies AFTER aggregation."],
    solution: "SELECT country, COUNT(*) AS user_count FROM users GROUP BY country HAVING COUNT(*) > 1;",
    explanation: "WHERE filters rows before grouping; HAVING filters groups.",
    complexity: "O(n)",
    conceptsLearned: ["HAVING"],
  },

  // --- CASE WHEN ---
  {
    id: "cse-01",
    number: nx(),
    title: "Price buckets",
    topic: "case-when",
    difficulty: "Intermediate",
    estMinutes: 6,
    xp: 25,
    concepts: ["CASE"],
    tags: ["expression"],
    domain: "E-Commerce",
    problem:
      "For each inventory item return name and a bucket: 'cheap' (<20), 'mid' (20-100), 'premium' (>100).",
    dbDescription: "inventory",
    sampleInput: "",
    expectedOutput: "name, bucket.",
    starterSql: "",
    hints: ["CASE WHEN … THEN … ELSE … END.", "Boundaries matter — check them."],
    solution:
      "SELECT name,\n  CASE WHEN price < 20 THEN 'cheap' WHEN price <= 100 THEN 'mid' ELSE 'premium' END AS bucket\nFROM inventory;",
    explanation: "CASE is a portable conditional expression.",
    complexity: "O(n)",
    conceptsLearned: ["CASE"],
  },

  // --- String Functions ---
  {
    id: "str-01",
    number: nx(),
    title: "Uppercase names",
    topic: "string-functions",
    difficulty: "Beginner",
    estMinutes: 3,
    xp: 10,
    concepts: ["UPPER"],
    tags: ["string"],
    domain: "E-Commerce",
    problem: "Return the name column uppercased, aliased as upper_name.",
    dbDescription: "users",
    sampleInput: "",
    expectedOutput: "upper_name column.",
    starterSql: "",
    hints: ["UPPER(str).", "Alias with AS."],
    solution: "SELECT UPPER(name) AS upper_name FROM users;",
    explanation: "UPPER / LOWER are standard case-conversion functions.",
    complexity: "O(n)",
    conceptsLearned: ["UPPER"],
  },
  {
    id: "str-02",
    number: nx(),
    title: "Emails ending in .com",
    topic: "string-functions",
    difficulty: "Intermediate",
    estMinutes: 4,
    xp: 20,
    concepts: ["LIKE"],
    tags: ["string", "pattern"],
    domain: "E-Commerce",
    problem: "Return users whose email ends with '.com'.",
    dbDescription: "users",
    sampleInput: "",
    expectedOutput: "Matching users.",
    starterSql: "",
    hints: ["LIKE '%.com'.", "% matches any sequence."],
    solution: "SELECT * FROM users WHERE email LIKE '%.com';",
    explanation: "LIKE supports % and _ wildcards.",
    complexity: "O(n)",
    conceptsLearned: ["LIKE"],
  },

  // --- Date Functions ---
  {
    id: "dt-01",
    number: nx(),
    title: "Recent signups",
    topic: "date-functions",
    difficulty: "Intermediate",
    estMinutes: 5,
    xp: 20,
    concepts: ["date comparison"],
    tags: ["date"],
    domain: "E-Commerce",
    problem: "Return users who signed up on or after 2024-01-01.",
    dbDescription: "users",
    sampleInput: "",
    expectedOutput: "Recent users.",
    starterSql: "",
    hints: ["Compare signup_date to a literal.", "Dates sort lexicographically as ISO strings."],
    solution: "SELECT * FROM users WHERE signup_date >= '2024-01-01';",
    explanation: "ISO 8601 date strings compare correctly in most engines.",
    complexity: "O(n)",
    conceptsLearned: ["Date comparison"],
  },

  // --- Math Functions ---
  {
    id: "mth-01",
    number: nx(),
    title: "Round prices",
    topic: "math-functions",
    difficulty: "Beginner",
    estMinutes: 3,
    xp: 10,
    concepts: ["ROUND"],
    tags: ["math"],
    domain: "E-Commerce",
    problem: "Return item name and price rounded to whole numbers, aliased as rounded.",
    dbDescription: "inventory",
    sampleInput: "",
    expectedOutput: "name, rounded.",
    starterSql: "",
    hints: ["ROUND(price).", "Second arg = digits."],
    solution: "SELECT name, ROUND(price) AS rounded FROM inventory;",
    explanation: "ROUND rounds to the nearest integer or given precision.",
    complexity: "O(n)",
    conceptsLearned: ["ROUND"],
  },

  // --- NULL Handling ---
  {
    id: "nul-01",
    number: nx(),
    title: "Items with unknown rating",
    topic: "null-handling",
    difficulty: "Beginner",
    estMinutes: 4,
    xp: 15,
    concepts: ["IS NULL"],
    tags: ["null"],
    domain: "E-Commerce",
    problem: "Return inventory rows where rating IS NULL.",
    dbDescription: "inventory",
    sampleInput: "",
    expectedOutput: "Items without a rating.",
    starterSql: "",
    hints: ["IS NULL, not = NULL.", "NULL is never equal to anything."],
    solution: "SELECT * FROM inventory WHERE rating IS NULL;",
    explanation: "SQL NULL is unknown; comparisons with = always yield NULL/false.",
    complexity: "O(n)",
    conceptsLearned: ["IS NULL"],
  },
  {
    id: "nul-02",
    number: nx(),
    title: "Coalesce missing ratings",
    topic: "null-handling",
    difficulty: "Intermediate",
    estMinutes: 4,
    xp: 20,
    concepts: ["COALESCE"],
    tags: ["null"],
    domain: "E-Commerce",
    problem: "Return name and rating, replacing NULL ratings with 0. Alias as safe_rating.",
    dbDescription: "inventory",
    sampleInput: "",
    expectedOutput: "name, safe_rating.",
    starterSql: "",
    hints: ["COALESCE(value, default).", "Portable across engines."],
    solution: "SELECT name, COALESCE(rating, 0) AS safe_rating FROM inventory;",
    explanation: "COALESCE returns the first non-NULL argument.",
    complexity: "O(n)",
    conceptsLearned: ["COALESCE"],
  },

  // --- INNER JOIN ---
  {
    id: "inj-01",
    number: nx(),
    title: "Shipments with buyer name",
    topic: "inner-join",
    difficulty: "Intermediate",
    estMinutes: 6,
    xp: 25,
    concepts: ["INNER JOIN"],
    tags: ["join"],
    domain: "E-Commerce",
    problem: "Return shipment_id and user name for every shipment.",
    dbDescription: "shipments, users",
    sampleInput: "",
    expectedOutput: "shipment_id, name.",
    starterSql: "",
    hints: ["JOIN … ON.", "Match user_id."],
    solution:
      "SELECT s.shipment_id, u.name\nFROM shipments s\nJOIN users u ON u.user_id = s.user_id;",
    explanation: "INNER JOIN returns rows that match in both tables.",
    complexity: "O(n)",
    conceptsLearned: ["INNER JOIN"],
  },

  // --- LEFT JOIN ---
  {
    id: "lj-01",
    number: nx(),
    title: "All users and their shipments",
    topic: "left-join",
    difficulty: "Intermediate",
    estMinutes: 7,
    xp: 25,
    concepts: ["LEFT JOIN"],
    tags: ["join"],
    domain: "E-Commerce",
    problem:
      "Return every user and, if present, their shipment_id. Users with no shipments should still appear.",
    dbDescription: "users, shipments",
    sampleInput: "",
    expectedOutput: "user name, shipment_id (may be NULL).",
    starterSql: "",
    hints: ["LEFT JOIN keeps the left table.", "Missing right rows produce NULLs."],
    solution:
      "SELECT u.name, s.shipment_id\nFROM users u\nLEFT JOIN shipments s ON s.user_id = u.user_id;",
    explanation: "LEFT JOIN preserves every row from the left input.",
    complexity: "O(n)",
    conceptsLearned: ["LEFT JOIN"],
  },

  // --- RIGHT JOIN ---
  {
    id: "rj-01",
    number: nx(),
    title: "Every item and its shipments",
    topic: "right-join",
    difficulty: "Advanced",
    estMinutes: 7,
    xp: 30,
    concepts: ["RIGHT JOIN"],
    tags: ["join"],
    domain: "E-Commerce",
    problem: "Return each inventory item alongside any shipments (item may have none).",
    dbDescription: "shipments, inventory",
    sampleInput: "",
    expectedOutput: "item name, shipment_id.",
    starterSql: "",
    hints: [
      "RIGHT JOIN keeps the right table (SQLite doesn't support it — flip to LEFT JOIN).",
      "Match on item_id.",
    ],
    solution:
      "SELECT i.name, s.shipment_id\nFROM inventory i\nLEFT JOIN shipments s ON s.item_id = i.item_id;",
    altSolution:
      "SELECT i.name, s.shipment_id\nFROM shipments s\nRIGHT JOIN inventory i ON s.item_id = i.item_id;",
    explanation: "RIGHT JOIN is mirror of LEFT JOIN. Not all engines support it; flip and use LEFT JOIN.",
    complexity: "O(n)",
    conceptsLearned: ["RIGHT JOIN"],
  },

  // --- FULL OUTER JOIN ---
  {
    id: "foj-01",
    number: nx(),
    title: "Everyone and everything shipped",
    topic: "full-outer-join",
    difficulty: "Advanced",
    estMinutes: 8,
    xp: 30,
    concepts: ["FULL OUTER JOIN", "UNION"],
    tags: ["join"],
    domain: "E-Commerce",
    problem:
      "Return the union of users and shipments matched on user_id — include unmatched rows on both sides.",
    dbDescription: "users, shipments",
    sampleInput: "",
    expectedOutput: "user_id from either side, shipment_id nullable.",
    starterSql: "",
    hints: [
      "FULL OUTER JOIN when supported.",
      "Emulate with LEFT JOIN UNION RIGHT-simulated on unsupported engines.",
    ],
    solution:
      "SELECT u.user_id, s.shipment_id\nFROM users u LEFT JOIN shipments s ON s.user_id = u.user_id\nUNION\nSELECT u.user_id, s.shipment_id\nFROM shipments s LEFT JOIN users u ON u.user_id = s.user_id;",
    explanation: "FULL OUTER JOIN keeps both sides. Emulate with two LEFT JOINs + UNION.",
    complexity: "O(n)",
    conceptsLearned: ["FULL OUTER JOIN"],
  },

  // --- SELF JOIN ---
  {
    id: "sj-01",
    number: nx(),
    title: "Country buddies",
    topic: "self-join",
    difficulty: "Advanced",
    estMinutes: 8,
    xp: 30,
    concepts: ["Self join"],
    tags: ["join"],
    domain: "E-Commerce",
    problem:
      "Return distinct pairs (a.name, b.name) of users from the same country where a.user_id < b.user_id.",
    dbDescription: "users",
    sampleInput: "",
    expectedOutput: "pair of names.",
    starterSql: "",
    hints: ["JOIN users to itself with two aliases.", "Restrict with < to avoid duplicates."],
    solution:
      "SELECT a.name AS name_a, b.name AS name_b\nFROM users a JOIN users b ON a.country = b.country AND a.user_id < b.user_id;",
    explanation: "A self-join is a JOIN of a table with itself under different aliases.",
    complexity: "O(n^2) worst case",
    conceptsLearned: ["Self-join"],
  },

  // --- CROSS JOIN ---
  {
    id: "cj-01",
    number: nx(),
    title: "Cartesian product size",
    topic: "cross-join",
    difficulty: "Intermediate",
    estMinutes: 5,
    xp: 20,
    concepts: ["CROSS JOIN"],
    tags: ["join"],
    domain: "E-Commerce",
    problem: "Return the number of (user, item) pairs via CROSS JOIN. One column pair_count.",
    dbDescription: "users, inventory",
    sampleInput: "",
    expectedOutput: "single row.",
    starterSql: "",
    hints: ["CROSS JOIN yields Cartesian product.", "COUNT(*)."],
    solution: "SELECT COUNT(*) AS pair_count FROM users CROSS JOIN inventory;",
    explanation: "CROSS JOIN pairs every left row with every right row.",
    complexity: "O(n·m)",
    conceptsLearned: ["CROSS JOIN"],
  },

  // --- Multi-table Joins ---
  {
    id: "mtj-01",
    number: nx(),
    title: "Shipment report",
    topic: "multi-table-joins",
    difficulty: "Advanced",
    estMinutes: 8,
    xp: 30,
    concepts: ["multiple JOIN"],
    tags: ["join"],
    domain: "E-Commerce",
    problem: "For each shipment return the buyer name and item name.",
    dbDescription: "shipments, users, inventory",
    sampleInput: "",
    expectedOutput: "user name, item name.",
    starterSql: "",
    hints: ["Two JOINs.", "One to users, one to inventory."],
    solution:
      "SELECT u.name AS buyer, i.name AS item\nFROM shipments s\nJOIN users u ON u.user_id = s.user_id\nJOIN inventory i ON i.item_id = s.item_id;",
    explanation: "Chain JOINs left-to-right, matching by keys.",
    complexity: "O(n)",
    conceptsLearned: ["Multi-JOIN"],
  },

  // --- UNION ---
  {
    id: "un-01",
    number: nx(),
    title: "All identifiers",
    topic: "union",
    difficulty: "Intermediate",
    estMinutes: 5,
    xp: 20,
    concepts: ["UNION ALL"],
    tags: ["set"],
    domain: "E-Commerce",
    problem: "Return user_id from users and user_id from shipments in a single column id, using UNION ALL.",
    dbDescription: "users, shipments",
    sampleInput: "",
    expectedOutput: "one column id.",
    starterSql: "",
    hints: ["UNION ALL keeps duplicates.", "UNION dedupes."],
    solution: "SELECT user_id AS id FROM users\nUNION ALL\nSELECT user_id FROM shipments;",
    explanation: "UNION vs UNION ALL — the latter is cheaper and keeps duplicates.",
    complexity: "O(n+m)",
    conceptsLearned: ["UNION ALL"],
  },

  // --- Subqueries ---
  {
    id: "sub-01",
    number: nx(),
    title: "Users with any shipment",
    topic: "subqueries",
    difficulty: "Intermediate",
    estMinutes: 6,
    xp: 25,
    concepts: ["subquery", "IN"],
    tags: ["subquery"],
    domain: "E-Commerce",
    problem: "Return users whose user_id appears in shipments.user_id.",
    dbDescription: "users, shipments",
    sampleInput: "",
    expectedOutput: "users with at least one shipment.",
    starterSql: "",
    hints: ["Use IN (SELECT …).", "Or EXISTS."],
    solution: "SELECT * FROM users WHERE user_id IN (SELECT user_id FROM shipments);",
    explanation: "Scalar and list subqueries can drive IN clauses.",
    complexity: "O(n)",
    conceptsLearned: ["Subquery"],
  },

  // --- Correlated Subqueries ---
  {
    id: "cor-01",
    number: nx(),
    title: "Users above avg shipments",
    topic: "correlated-subqueries",
    difficulty: "Advanced",
    estMinutes: 10,
    xp: 35,
    concepts: ["correlated subquery"],
    tags: ["subquery"],
    domain: "E-Commerce",
    problem:
      "Return users whose shipment count is greater than the average shipment count across users.",
    dbDescription: "users, shipments",
    sampleInput: "",
    expectedOutput: "matching users with their shipment count.",
    starterSql: "",
    hints: ["Compute per-user count.", "Compare against a scalar avg subquery."],
    solution:
      "SELECT u.user_id, u.name, (SELECT COUNT(*) FROM shipments s WHERE s.user_id = u.user_id) AS n\nFROM users u\nWHERE (SELECT COUNT(*) FROM shipments s WHERE s.user_id = u.user_id) >\n      (SELECT AVG(cnt) FROM (SELECT COUNT(*) AS cnt FROM shipments GROUP BY user_id) t);",
    explanation: "A correlated subquery references the outer row.",
    complexity: "O(n²) if not optimized",
    conceptsLearned: ["Correlated subquery"],
  },

  // --- EXISTS / NOT EXISTS ---
  {
    id: "ex-01",
    number: nx(),
    title: "Users without shipments",
    topic: "exists",
    difficulty: "Intermediate",
    estMinutes: 6,
    xp: 25,
    concepts: ["NOT EXISTS"],
    tags: ["exists"],
    domain: "E-Commerce",
    problem: "Return users for whom no shipment exists.",
    dbDescription: "users, shipments",
    sampleInput: "",
    expectedOutput: "users without a shipment.",
    starterSql: "",
    hints: ["NOT EXISTS (SELECT 1 …).", "Correlate on user_id."],
    solution:
      "SELECT * FROM users u\nWHERE NOT EXISTS (SELECT 1 FROM shipments s WHERE s.user_id = u.user_id);",
    explanation: "EXISTS is a boolean test; the SELECT list inside is ignored.",
    complexity: "O(n·m)",
    conceptsLearned: ["EXISTS", "NOT EXISTS"],
  },

  // --- ANY / ALL ---
  {
    id: "any-01",
    number: nx(),
    title: "Priced above cheapest",
    topic: "any-all",
    difficulty: "Advanced",
    estMinutes: 6,
    xp: 25,
    concepts: ["ANY"],
    tags: ["quantified"],
    domain: "E-Commerce",
    problem: "Return inventory rows whose price is greater than ANY price in the same table.",
    dbDescription: "inventory",
    sampleInput: "",
    expectedOutput: "items above the minimum.",
    starterSql: "",
    hints: ["> ANY equals > MIN.", "Compare against the subquery."],
    solution:
      "SELECT * FROM inventory\nWHERE price > ANY (SELECT price FROM inventory);",
    explanation: "> ANY means greater than at least one row in the set.",
    complexity: "O(n)",
    conceptsLearned: ["ANY", "ALL"],
  },

  // --- CTE ---
  {
    id: "cte-01",
    number: nx(),
    title: "Per-country user counts via CTE",
    topic: "cte",
    difficulty: "Intermediate",
    estMinutes: 6,
    xp: 25,
    concepts: ["WITH"],
    tags: ["cte"],
    domain: "E-Commerce",
    problem:
      "Using a CTE named country_counts, compute users per country, then return only countries with more than one user.",
    dbDescription: "users",
    sampleInput: "",
    expectedOutput: "country, n where n > 1.",
    starterSql: "",
    hints: ["WITH cte AS (...) SELECT … FROM cte.", "Aggregate in the CTE."],
    solution:
      "WITH country_counts AS (\n  SELECT country, COUNT(*) AS n FROM users GROUP BY country\n)\nSELECT * FROM country_counts WHERE n > 1;",
    explanation: "CTEs improve readability and enable reuse within a single query.",
    complexity: "O(n)",
    conceptsLearned: ["CTE"],
  },

  // --- Recursive CTE ---
  {
    id: "rcte-01",
    number: nx(),
    title: "Numbers 1..5",
    topic: "recursive-cte",
    difficulty: "Advanced",
    estMinutes: 8,
    xp: 35,
    concepts: ["recursive CTE"],
    tags: ["cte"],
    domain: "E-Commerce",
    problem: "Using a recursive CTE, generate the numbers 1 through 5 as a single column n.",
    dbDescription: "no tables required",
    sampleInput: "",
    expectedOutput: "five rows: 1..5.",
    starterSql: "",
    hints: ["WITH RECURSIVE.", "Base case UNION ALL recursive step."],
    solution:
      "WITH RECURSIVE nums(n) AS (\n  SELECT 1\n  UNION ALL\n  SELECT n + 1 FROM nums WHERE n < 5\n)\nSELECT n FROM nums;",
    explanation: "Recursive CTEs iterate a base + inductive step until the step yields no rows.",
    complexity: "O(k)",
    conceptsLearned: ["Recursive CTE"],
  },

  // --- Window Functions ---
  {
    id: "win-01",
    number: nx(),
    title: "Running item count",
    topic: "window-functions",
    difficulty: "Advanced",
    estMinutes: 8,
    xp: 35,
    concepts: ["window"],
    tags: ["window"],
    domain: "E-Commerce",
    problem: "Return name and a running COUNT(*) OVER (ORDER BY item_id) as running_n.",
    dbDescription: "inventory",
    sampleInput: "",
    expectedOutput: "name, running_n.",
    starterSql: "",
    hints: ["COUNT(*) OVER (ORDER BY …).", "No PARTITION BY needed."],
    solution:
      "SELECT name, COUNT(*) OVER (ORDER BY item_id) AS running_n FROM inventory;",
    explanation: "Window functions compute per-row values across a defined frame.",
    complexity: "O(n log n)",
    conceptsLearned: ["Window function"],
  },

  // --- ROW_NUMBER ---
  {
    id: "rn-01",
    number: nx(),
    title: "Rank items by price",
    topic: "row-number",
    difficulty: "Advanced",
    estMinutes: 6,
    xp: 30,
    concepts: ["ROW_NUMBER"],
    tags: ["window"],
    domain: "E-Commerce",
    problem: "Return name, price, and ROW_NUMBER() OVER (ORDER BY price DESC) as rn.",
    dbDescription: "inventory",
    sampleInput: "",
    expectedOutput: "name, price, rn.",
    starterSql: "",
    hints: ["ROW_NUMBER() OVER (ORDER BY …).", "Ties broken arbitrarily."],
    solution:
      "SELECT name, price, ROW_NUMBER() OVER (ORDER BY price DESC) AS rn FROM inventory;",
    explanation: "ROW_NUMBER assigns a unique sequence per row within the window.",
    complexity: "O(n log n)",
    conceptsLearned: ["ROW_NUMBER"],
  },

  // --- RANK ---
  {
    id: "rk-01",
    number: nx(),
    title: "Rank users by signup",
    topic: "rank",
    difficulty: "Advanced",
    estMinutes: 6,
    xp: 30,
    concepts: ["RANK"],
    tags: ["window"],
    domain: "E-Commerce",
    problem: "Return name and RANK() OVER (ORDER BY signup_date) as rk.",
    dbDescription: "users",
    sampleInput: "",
    expectedOutput: "name, rk.",
    starterSql: "",
    hints: ["Ties share a rank.", "Next rank skips."],
    solution: "SELECT name, RANK() OVER (ORDER BY signup_date) AS rk FROM users;",
    explanation: "RANK leaves gaps on ties; DENSE_RANK does not.",
    complexity: "O(n log n)",
    conceptsLearned: ["RANK"],
  },

  // --- DENSE_RANK ---
  {
    id: "drk-01",
    number: nx(),
    title: "Dense ranks by rating",
    topic: "dense-rank",
    difficulty: "Advanced",
    estMinutes: 6,
    xp: 30,
    concepts: ["DENSE_RANK"],
    tags: ["window"],
    domain: "E-Commerce",
    problem: "Return name, rating, and DENSE_RANK() OVER (ORDER BY rating DESC) as drk.",
    dbDescription: "inventory",
    sampleInput: "",
    expectedOutput: "name, rating, drk.",
    starterSql: "",
    hints: ["No gaps.", "Ties share a rank."],
    solution:
      "SELECT name, rating, DENSE_RANK() OVER (ORDER BY rating DESC) AS drk FROM inventory;",
    explanation: "DENSE_RANK yields consecutive ranks even with ties.",
    complexity: "O(n log n)",
    conceptsLearned: ["DENSE_RANK"],
  },

  // --- LEAD ---
  {
    id: "ld-01",
    number: nx(),
    title: "Next user's signup date",
    topic: "lead",
    difficulty: "Advanced",
    estMinutes: 6,
    xp: 30,
    concepts: ["LEAD"],
    tags: ["window"],
    domain: "E-Commerce",
    problem: "Return name, signup_date, and LEAD(signup_date) OVER (ORDER BY signup_date) as next_signup.",
    dbDescription: "users",
    sampleInput: "",
    expectedOutput: "three columns.",
    starterSql: "",
    hints: ["LEAD looks forward.", "Last row will be NULL."],
    solution:
      "SELECT name, signup_date, LEAD(signup_date) OVER (ORDER BY signup_date) AS next_signup FROM users;",
    explanation: "LEAD returns a value from a later row in the window.",
    complexity: "O(n log n)",
    conceptsLearned: ["LEAD"],
  },

  // --- LAG ---
  {
    id: "lg-01",
    number: nx(),
    title: "Previous item price",
    topic: "lag",
    difficulty: "Advanced",
    estMinutes: 6,
    xp: 30,
    concepts: ["LAG"],
    tags: ["window"],
    domain: "E-Commerce",
    problem: "Return name, price, and LAG(price) OVER (ORDER BY item_id) as prev_price.",
    dbDescription: "inventory",
    sampleInput: "",
    expectedOutput: "name, price, prev_price.",
    starterSql: "",
    hints: ["LAG looks backward.", "First row will be NULL."],
    solution:
      "SELECT name, price, LAG(price) OVER (ORDER BY item_id) AS prev_price FROM inventory;",
    explanation: "LAG returns a value from an earlier row in the window.",
    complexity: "O(n log n)",
    conceptsLearned: ["LAG"],
  },

  // --- PARTITION BY ---
  {
    id: "pt-01",
    number: nx(),
    title: "Rank items within category",
    topic: "partition-by",
    difficulty: "Interview",
    estMinutes: 10,
    xp: 40,
    concepts: ["PARTITION BY"],
    tags: ["window", "interview"],
    domain: "E-Commerce",
    problem:
      "For each category, rank items by price descending. Return name, category, price, and rank_in_cat.",
    dbDescription: "inventory",
    sampleInput: "",
    expectedOutput: "name, category, price, rank_in_cat.",
    starterSql: "",
    hints: ["OVER (PARTITION BY category ORDER BY price DESC).", "Ranks reset per partition."],
    solution:
      "SELECT name, category, price,\n  RANK() OVER (PARTITION BY category ORDER BY price DESC) AS rank_in_cat\nFROM inventory;",
    explanation: "PARTITION BY resets the window frame for each partition value.",
    complexity: "O(n log n)",
    conceptsLearned: ["PARTITION BY"],
  },

  // --- Views ---
  {
    id: "vw-01",
    number: nx(),
    title: "Create a view",
    topic: "views",
    difficulty: "Intermediate",
    estMinutes: 5,
    xp: 20,
    concepts: ["CREATE VIEW"],
    tags: ["ddl"],
    domain: "E-Commerce",
    problem: "Create a view named active_users returning only active users, then SELECT * from it.",
    dbDescription: "users",
    sampleInput: "",
    expectedOutput: "active users.",
    starterSql: "",
    hints: ["CREATE VIEW name AS SELECT …", "Then SELECT * FROM name."],
    solution:
      "CREATE VIEW active_users AS SELECT * FROM users WHERE is_active = 1;\nSELECT * FROM active_users;",
    explanation: "Views are stored queries you can reference like tables.",
    complexity: "N/A",
    conceptsLearned: ["Views"],
  },

  // --- Indexes ---
  {
    id: "idx-01",
    number: nx(),
    title: "Index a lookup column",
    topic: "indexes",
    difficulty: "Intermediate",
    estMinutes: 4,
    xp: 20,
    concepts: ["CREATE INDEX"],
    tags: ["performance"],
    domain: "E-Commerce",
    problem: "Create an index named idx_users_country on users(country).",
    dbDescription: "users",
    sampleInput: "",
    expectedOutput: "index created (no rows).",
    starterSql: "",
    hints: ["CREATE INDEX name ON table(col).", "Speeds up filters on that column."],
    solution: "CREATE INDEX idx_users_country ON users(country);",
    explanation: "Indexes are data structures accelerating lookups.",
    complexity: "O(log n) lookups",
    conceptsLearned: ["Indexes"],
  },

  // --- Transactions ---
  {
    id: "tx-01",
    number: nx(),
    title: "Wrap an update in a transaction",
    topic: "transactions",
    difficulty: "Intermediate",
    estMinutes: 5,
    xp: 25,
    concepts: ["BEGIN", "COMMIT"],
    tags: ["transactions"],
    domain: "E-Commerce",
    problem: "Inside a transaction, set is_active = 0 for user_id = 1 and COMMIT.",
    dbDescription: "users",
    sampleInput: "",
    expectedOutput: "committed update.",
    starterSql: "",
    hints: ["BEGIN; … COMMIT;", "ROLLBACK to undo."],
    solution: "BEGIN;\nUPDATE users SET is_active = 0 WHERE user_id = 1;\nCOMMIT;",
    explanation: "Transactions group statements into atomic units.",
    complexity: "N/A",
    conceptsLearned: ["Transactions"],
  },

  // --- Database Design ---
  {
    id: "dd-01",
    number: nx(),
    title: "Model a simple orders schema",
    topic: "database-design",
    difficulty: "Interview",
    estMinutes: 15,
    xp: 45,
    concepts: ["schema design"],
    tags: ["design", "interview"],
    domain: "E-Commerce",
    problem:
      "Design and create an 'orders' table linking users to inventory with quantity and created_at. Include foreign keys.",
    dbDescription: "users, inventory",
    sampleInput: "",
    expectedOutput: "orders table created.",
    starterSql: "",
    hints: ["Use INTEGER PRIMARY KEY.", "REFERENCES adds a foreign key."],
    solution:
      "CREATE TABLE orders (\n  order_id INTEGER PRIMARY KEY,\n  user_id INTEGER REFERENCES users(user_id),\n  item_id INTEGER REFERENCES inventory(item_id),\n  quantity INTEGER NOT NULL,\n  created_at TEXT NOT NULL\n);",
    explanation: "Foreign keys enforce referential integrity between tables.",
    complexity: "N/A",
    conceptsLearned: ["Schema design", "FK"],
  },

  // --- Normalization ---
  {
    id: "nrm-01",
    number: nx(),
    title: "Extract a lookup table",
    topic: "normalization",
    difficulty: "Advanced",
    estMinutes: 10,
    xp: 35,
    concepts: ["3NF"],
    tags: ["design"],
    domain: "E-Commerce",
    problem:
      "Create a categories table (category_id, name) from the DISTINCT categories currently in inventory.",
    dbDescription: "inventory",
    sampleInput: "",
    expectedOutput: "categories table populated.",
    starterSql: "",
    hints: ["CREATE TABLE then INSERT SELECT DISTINCT.", "You can use a row_number() to generate ids."],
    solution:
      "CREATE TABLE categories (category_id INTEGER PRIMARY KEY, name TEXT UNIQUE);\nINSERT INTO categories(name) SELECT DISTINCT category FROM inventory;",
    explanation: "Extracting repeated values into a lookup reduces redundancy (a step toward 3NF).",
    complexity: "N/A",
    conceptsLearned: ["Normalization", "Lookup tables"],
  },

  // --- Performance ---
  {
    id: "prf-01",
    number: nx(),
    title: "Explain a filter query",
    topic: "performance",
    difficulty: "Interview",
    estMinutes: 8,
    xp: 40,
    concepts: ["EXPLAIN"],
    tags: ["performance", "interview"],
    domain: "E-Commerce",
    problem: "Return the query plan for `SELECT * FROM users WHERE country = 'US'` using EXPLAIN.",
    dbDescription: "users",
    sampleInput: "",
    expectedOutput: "query plan rows.",
    starterSql: "",
    hints: ["EXPLAIN <stmt>.", "SQLite: EXPLAIN QUERY PLAN <stmt>."],
    solution: "EXPLAIN QUERY PLAN SELECT * FROM users WHERE country = 'US';",
    altSolution: "EXPLAIN SELECT * FROM users WHERE country = 'US';",
    explanation: "Query planners expose how the engine will execute your SQL — use it to catch full scans.",
    complexity: "N/A",
    conceptsLearned: ["EXPLAIN"],
  },
];
