import type { DomainDef } from "./types";

/**
 * 22 professional SQL practice domains. Each domain has a consistent 3-table
 * shape (entity → event → item) so templates can generate portable challenges
 * against real-looking schemas.
 */
export const DOMAINS: DomainDef[] = [
  {
    id: "healthcare",
    label: "Healthcare",
    emoji: "🏥",
    entity: { name: "patients", label: "patient", cols: "patient_id, name, dob, gender, city, insurance", keyCol: "patient_id", textCol: "name", regionCol: "city" },
    event: { name: "appointments", label: "appointment", cols: "appointment_id, patient_id, doctor_id, appointment_date, status, fee", dateCol: "appointment_date", amountCol: "fee", statusCol: "status", statusValues: ["Scheduled", "Completed", "Cancelled", "No-show"], entityFk: "patient_id", itemFk: "doctor_id" },
    item: { name: "doctors", label: "doctor", cols: "doctor_id, name, specialty, years_experience, consultation_fee", categoryCol: "specialty", priceCol: "consultation_fee", textCol: "name" },
  },
  {
    id: "retail",
    label: "Retail",
    emoji: "🛍️",
    entity: { name: "customers", label: "customer", cols: "customer_id, name, city, membership_level, join_date", keyCol: "customer_id", textCol: "name", regionCol: "city" },
    event: { name: "sales", label: "sale", cols: "sale_id, customer_id, product_id, sale_date, quantity, total_amount, status", dateCol: "sale_date", amountCol: "total_amount", statusCol: "status", statusValues: ["Paid", "Refunded", "Pending"], entityFk: "customer_id", itemFk: "product_id" },
    item: { name: "products", label: "product", cols: "product_id, name, category, price, stock", categoryCol: "category", priceCol: "price", textCol: "name" },
  },
  {
    id: "banking",
    label: "Banking",
    emoji: "🏦",
    entity: { name: "customers", label: "customer", cols: "customer_id, name, city, credit_score, occupation", keyCol: "customer_id", textCol: "name", regionCol: "city" },
    event: { name: "transactions", label: "transaction", cols: "txn_id, customer_id, account_id, txn_date, amount, txn_type", dateCol: "txn_date", amountCol: "amount", statusCol: "txn_type", statusValues: ["Deposit", "Withdrawal", "Transfer", "Fee"], entityFk: "customer_id", itemFk: "account_id" },
    item: { name: "accounts", label: "account", cols: "account_id, customer_id, account_type, balance, opened_at", categoryCol: "account_type", priceCol: "balance", textCol: "account_type" },
  },
  {
    id: "education",
    label: "Education",
    emoji: "🎓",
    entity: { name: "students", label: "student", cols: "student_id, name, major, city, enrollment_year", keyCol: "student_id", textCol: "name", regionCol: "city" },
    event: { name: "enrollments", label: "enrollment", cols: "enrollment_id, student_id, course_id, term, grade, credits", dateCol: "term", amountCol: "credits", statusCol: "grade", statusValues: ["A", "B", "C", "D", "F"], entityFk: "student_id", itemFk: "course_id" },
    item: { name: "courses", label: "course", cols: "course_id, title, department, credits, instructor", categoryCol: "department", priceCol: "credits", textCol: "title" },
  },
  {
    id: "ecommerce",
    label: "E-Commerce",
    emoji: "🛒",
    entity: { name: "users", label: "user", cols: "user_id, name, email, country, signup_date", keyCol: "user_id", textCol: "name", regionCol: "country" },
    event: { name: "orders", label: "order", cols: "order_id, user_id, item_id, order_date, quantity, total, status", dateCol: "order_date", amountCol: "total", statusCol: "status", statusValues: ["Placed", "Shipped", "Delivered", "Returned"], entityFk: "user_id", itemFk: "item_id" },
    item: { name: "inventory", label: "product", cols: "item_id, name, category, price, rating, stock", categoryCol: "category", priceCol: "price", textCol: "name" },
  },
  {
    id: "hr",
    label: "Human Resources",
    emoji: "👥",
    entity: { name: "employees", label: "employee", cols: "employee_id, name, department, hire_date, salary, manager_id", keyCol: "employee_id", textCol: "name", regionCol: "department" },
    event: { name: "attendance", label: "attendance record", cols: "record_id, employee_id, work_date, hours, project_id, status", dateCol: "work_date", amountCol: "hours", statusCol: "status", statusValues: ["Present", "Remote", "Leave", "Sick"], entityFk: "employee_id", itemFk: "project_id" },
    item: { name: "projects", label: "project", cols: "project_id, name, department, budget, status", categoryCol: "department", priceCol: "budget", textCol: "name" },
  },
  {
    id: "insurance",
    label: "Insurance",
    emoji: "📋",
    entity: { name: "policyholders", label: "policyholder", cols: "holder_id, name, city, dob, credit_score", keyCol: "holder_id", textCol: "name", regionCol: "city" },
    event: { name: "claims", label: "claim", cols: "claim_id, holder_id, policy_id, claim_date, amount, status", dateCol: "claim_date", amountCol: "amount", statusCol: "status", statusValues: ["Filed", "Approved", "Denied", "Paid"], entityFk: "holder_id", itemFk: "policy_id" },
    item: { name: "policies", label: "policy", cols: "policy_id, type, premium, coverage_amount, term_years", categoryCol: "type", priceCol: "premium", textCol: "type" },
  },
  {
    id: "manufacturing",
    label: "Manufacturing",
    emoji: "🏭",
    entity: { name: "suppliers", label: "supplier", cols: "supplier_id, name, country, rating, contract_start", keyCol: "supplier_id", textCol: "name", regionCol: "country" },
    event: { name: "shipments", label: "shipment", cols: "shipment_id, supplier_id, part_id, ship_date, quantity, cost, status", dateCol: "ship_date", amountCol: "cost", statusCol: "status", statusValues: ["Ordered", "InTransit", "Received", "Rejected"], entityFk: "supplier_id", itemFk: "part_id" },
    item: { name: "parts", label: "part", cols: "part_id, name, category, unit_cost, lead_time_days", categoryCol: "category", priceCol: "unit_cost", textCol: "name" },
  },
  {
    id: "travel",
    label: "Travel",
    emoji: "✈️",
    entity: { name: "travelers", label: "traveler", cols: "traveler_id, name, country, loyalty_tier, join_date", keyCol: "traveler_id", textCol: "name", regionCol: "country" },
    event: { name: "bookings", label: "booking", cols: "booking_id, traveler_id, flight_id, book_date, price, status", dateCol: "book_date", amountCol: "price", statusCol: "status", statusValues: ["Confirmed", "Cancelled", "Completed"], entityFk: "traveler_id", itemFk: "flight_id" },
    item: { name: "flights", label: "flight", cols: "flight_id, airline, origin, destination, base_price", categoryCol: "airline", priceCol: "base_price", textCol: "airline" },
  },
  {
    id: "hospitality",
    label: "Hospitality",
    emoji: "🏨",
    entity: { name: "guests", label: "guest", cols: "guest_id, name, country, vip_status, join_date", keyCol: "guest_id", textCol: "name", regionCol: "country" },
    event: { name: "reservations", label: "reservation", cols: "reservation_id, guest_id, room_id, checkin_date, nights, total, status", dateCol: "checkin_date", amountCol: "total", statusCol: "status", statusValues: ["Booked", "CheckedIn", "CheckedOut", "Cancelled"], entityFk: "guest_id", itemFk: "room_id" },
    item: { name: "rooms", label: "room", cols: "room_id, hotel, room_type, nightly_rate, capacity", categoryCol: "room_type", priceCol: "nightly_rate", textCol: "hotel" },
  },
  {
    id: "food-delivery",
    label: "Food Delivery",
    emoji: "🍔",
    entity: { name: "customers", label: "customer", cols: "customer_id, name, city, join_date, plan", keyCol: "customer_id", textCol: "name", regionCol: "city" },
    event: { name: "orders", label: "order", cols: "order_id, customer_id, restaurant_id, order_time, total, status, delivery_minutes", dateCol: "order_time", amountCol: "total", statusCol: "status", statusValues: ["Placed", "Prepared", "Delivered", "Cancelled"], entityFk: "customer_id", itemFk: "restaurant_id" },
    item: { name: "restaurants", label: "restaurant", cols: "restaurant_id, name, cuisine, city, rating", categoryCol: "cuisine", priceCol: "rating", textCol: "name" },
  },
  {
    id: "ride-sharing",
    label: "Ride Sharing",
    emoji: "🚗",
    entity: { name: "riders", label: "rider", cols: "rider_id, name, city, join_date, rating", keyCol: "rider_id", textCol: "name", regionCol: "city" },
    event: { name: "trips", label: "trip", cols: "trip_id, rider_id, driver_id, trip_time, distance_km, fare, status", dateCol: "trip_time", amountCol: "fare", statusCol: "status", statusValues: ["Requested", "Completed", "Cancelled"], entityFk: "rider_id", itemFk: "driver_id" },
    item: { name: "drivers", label: "driver", cols: "driver_id, name, city, car_type, rating", categoryCol: "car_type", priceCol: "rating", textCol: "name" },
  },
  {
    id: "sports",
    label: "Sports",
    emoji: "🏆",
    entity: { name: "players", label: "player", cols: "player_id, name, country, team_id, position", keyCol: "player_id", textCol: "name", regionCol: "country" },
    event: { name: "matches", label: "match", cols: "match_id, player_id, team_id, match_date, points_scored, minutes_played, result", dateCol: "match_date", amountCol: "points_scored", statusCol: "result", statusValues: ["Win", "Loss", "Draw"], entityFk: "player_id", itemFk: "team_id" },
    item: { name: "teams", label: "team", cols: "team_id, name, league, city, founded_year", categoryCol: "league", priceCol: "founded_year", textCol: "name" },
  },
  {
    id: "gaming",
    label: "Gaming",
    emoji: "🎮",
    entity: { name: "players", label: "player", cols: "player_id, username, country, signup_date, tier", keyCol: "player_id", textCol: "username", regionCol: "country" },
    event: { name: "sessions", label: "session", cols: "session_id, player_id, game_id, session_start, minutes_played, xp_earned, outcome", dateCol: "session_start", amountCol: "xp_earned", statusCol: "outcome", statusValues: ["Won", "Lost", "Quit"], entityFk: "player_id", itemFk: "game_id" },
    item: { name: "games", label: "game", cols: "game_id, title, genre, publisher, release_year", categoryCol: "genre", priceCol: "release_year", textCol: "title" },
  },
  {
    id: "movies",
    label: "Movies",
    emoji: "🎬",
    entity: { name: "viewers", label: "viewer", cols: "viewer_id, name, country, plan, signup_date", keyCol: "viewer_id", textCol: "name", regionCol: "country" },
    event: { name: "views", label: "view", cols: "view_id, viewer_id, movie_id, view_date, watch_minutes, rating, completed", dateCol: "view_date", amountCol: "watch_minutes", statusCol: "completed", statusValues: ["Y", "N"], entityFk: "viewer_id", itemFk: "movie_id" },
    item: { name: "movies", label: "movie", cols: "movie_id, title, genre, release_year, runtime_minutes", categoryCol: "genre", priceCol: "runtime_minutes", textCol: "title" },
  },
  {
    id: "music",
    label: "Music",
    emoji: "🎧",
    entity: { name: "listeners", label: "listener", cols: "listener_id, name, country, plan, signup_date", keyCol: "listener_id", textCol: "name", regionCol: "country" },
    event: { name: "plays", label: "play", cols: "play_id, listener_id, track_id, play_time, seconds_played, skipped", dateCol: "play_time", amountCol: "seconds_played", statusCol: "skipped", statusValues: ["Y", "N"], entityFk: "listener_id", itemFk: "track_id" },
    item: { name: "tracks", label: "track", cols: "track_id, title, artist, genre, duration_seconds", categoryCol: "genre", priceCol: "duration_seconds", textCol: "title" },
  },
  {
    id: "telecom",
    label: "Telecommunications",
    emoji: "📡",
    entity: { name: "subscribers", label: "subscriber", cols: "subscriber_id, name, city, plan, activation_date", keyCol: "subscriber_id", textCol: "name", regionCol: "city" },
    event: { name: "calls", label: "call", cols: "call_id, subscriber_id, tower_id, call_time, duration_seconds, cost, call_type", dateCol: "call_time", amountCol: "cost", statusCol: "call_type", statusValues: ["Local", "STD", "International", "Data"], entityFk: "subscriber_id", itemFk: "tower_id" },
    item: { name: "towers", label: "tower", cols: "tower_id, city, region, capacity, install_date", categoryCol: "region", priceCol: "capacity", textCol: "city" },
  },
  {
    id: "supply-chain",
    label: "Supply Chain",
    emoji: "📦",
    entity: { name: "warehouses", label: "warehouse", cols: "warehouse_id, name, city, capacity, opened_at", keyCol: "warehouse_id", textCol: "name", regionCol: "city" },
    event: { name: "movements", label: "movement", cols: "movement_id, warehouse_id, sku_id, move_date, quantity, cost, direction", dateCol: "move_date", amountCol: "cost", statusCol: "direction", statusValues: ["Inbound", "Outbound", "Transfer"], entityFk: "warehouse_id", itemFk: "sku_id" },
    item: { name: "skus", label: "SKU", cols: "sku_id, name, category, unit_cost, weight_kg", categoryCol: "category", priceCol: "unit_cost", textCol: "name" },
  },
  {
    id: "logistics",
    label: "Logistics",
    emoji: "🚚",
    entity: { name: "shippers", label: "shipper", cols: "shipper_id, name, country, tier, join_date", keyCol: "shipper_id", textCol: "name", regionCol: "country" },
    event: { name: "deliveries", label: "delivery", cols: "delivery_id, shipper_id, route_id, ship_date, weight_kg, cost, status", dateCol: "ship_date", amountCol: "cost", statusCol: "status", statusValues: ["Pending", "InTransit", "Delivered", "Failed"], entityFk: "shipper_id", itemFk: "route_id" },
    item: { name: "routes", label: "route", cols: "route_id, origin, destination, distance_km, avg_days", categoryCol: "destination", priceCol: "distance_km", textCol: "destination" },
  },
  {
    id: "real-estate",
    label: "Real Estate",
    emoji: "🏘️",
    entity: { name: "agents", label: "agent", cols: "agent_id, name, city, brokerage, join_date", keyCol: "agent_id", textCol: "name", regionCol: "city" },
    event: { name: "listings", label: "listing", cols: "listing_id, agent_id, property_id, list_date, list_price, status, days_on_market", dateCol: "list_date", amountCol: "list_price", statusCol: "status", statusValues: ["Active", "Pending", "Sold", "Withdrawn"], entityFk: "agent_id", itemFk: "property_id" },
    item: { name: "properties", label: "property", cols: "property_id, address, property_type, bedrooms, square_feet", categoryCol: "property_type", priceCol: "square_feet", textCol: "address" },
  },
  {
    id: "social-media",
    label: "Social Media",
    emoji: "💬",
    entity: { name: "users", label: "user", cols: "user_id, handle, country, signup_date, followers", keyCol: "user_id", textCol: "handle", regionCol: "country" },
    event: { name: "posts", label: "post", cols: "post_id, user_id, hashtag_id, post_time, likes, comments, post_type", dateCol: "post_time", amountCol: "likes", statusCol: "post_type", statusValues: ["Text", "Image", "Video", "Reel"], entityFk: "user_id", itemFk: "hashtag_id" },
    item: { name: "hashtags", label: "hashtag", cols: "hashtag_id, tag, category, uses_count, trending", categoryCol: "category", priceCol: "uses_count", textCol: "tag" },
  },
  {
    id: "finance",
    label: "Finance",
    emoji: "📈",
    entity: { name: "investors", label: "investor", cols: "investor_id, name, country, risk_profile, join_date", keyCol: "investor_id", textCol: "name", regionCol: "country" },
    event: { name: "trades", label: "trade", cols: "trade_id, investor_id, security_id, trade_time, quantity, price, side", dateCol: "trade_time", amountCol: "price", statusCol: "side", statusValues: ["Buy", "Sell"], entityFk: "investor_id", itemFk: "security_id" },
    item: { name: "securities", label: "security", cols: "security_id, symbol, sector, last_price, market_cap", categoryCol: "sector", priceCol: "last_price", textCol: "symbol" },
  },
];

export const DOMAIN_MAP = Object.fromEntries(DOMAINS.map((d) => [d.id, d])) as Record<string, DomainDef>;
export const DOMAIN_LABELS = DOMAINS.map((d) => d.label);
